name: notebooksenv
channels:
- conda-forge
dependencies:
- python==3.7.3
- pip==19.*
- cython==0.29.8
- numpy==1.16.4
- scipy==1.2.1
- matplotlib=3.0.3
- pip:
  - https://test.pypi.org/simple/ qutip==4.4.post3

